### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by pzq-xjtu** [yunguo224/NLCL#1]
Hello, thanks for sharing the excellent work. I meet some error.

1. File "NLCL-main/models/patchnce.py", line 34, in forward
      if self.opt.nce_includes_all_negatives_from_minibatch:
    AttributeError: 'Namespace' object has no attribute 'nce_includes_all_negatives_from_minibatch'

2. ModuleNotFoundError: No module named 'data.single_dataset' when I try to test it.

**Comment by Hello-Felix** [comment]
Same Error, Please @yunguo224 check the code, thank you

**Comment by yunguo224** [comment]
--nce_includes_all_negatives_from_minibatch should be set as False. Already updated in NLCL_model.py.
