### ISSUE TITLE
关于实验中使用的数据集的疑问

### ISSUE THREAD

**Issue by booker-max** [yunguo224/NLCL#3]
您好, 我想问一下实验中所使用的trainA和trainB有什么关系, cyclegan里面的trainA和trainB分别是有雨图和unpair的无雨图, 但是我不太理解你实验中的trainA和trainB有什么关系。

**Comment by lxy-1121** [comment]
您好，您弄清trainA和trainB如何设置了么？

**Comment by lxy-1121** [comment]
> 您好, 我想问一下实验中所使用的trainA和trainB有什么关系, cyclegan里面的trainA和trainB分别是有雨图和unpair的无雨图, 但是我不太理解你实验中的trainA和trainB有什么关系。

您弄清trainA和trainB如何设置了嘛

**Comment by yunguo224** [comment]
NLCL中的trainA与trainB设置与cycleGAN中的设置一致，分别为有雨图和非成对的清晰图像。

**Comment by lxy-1121** [comment]
> NLCL中的trainA与trainB设置与cycleGAN中的设置一致，分别为有雨图和非成对的清晰图像。

谢谢
